name: Pull Request

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  Run-Linter:
    uses: ./.github/workflows/linting.yaml
  Run-Unit-Tests:
    uses: ./.github/workflows/unit-testing.yaml
