# Runs next build on the project to verify that project successfully builds
name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        node-version: [18.x, 20.x, 22.x]
    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/competition-platform?schema=public"
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
