name: Runs linter on codebase

on:
  workflow_call:

jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Install dependencies
        run: pnpm install --force
      - name: Run Biome linter
        run: pnpm run lint

